### ISSUE TITLE
increase network flexibility

### ISSUE THREAD

**Issue by ttinoco** [ttinoco/PFNET#144]
- [x] symmetric connectors (e.g. when obj A is added to list of objects connected to bus B, bus B is set automatically as the bus to which obj A is connected, if not already, and viceversa
- [x] allow adding new objects to the network. For example, users should be able to create a new Generator(), set its properties, connect it to a bus. Then, new components can be integrated into the network using Network routines, e.g., network.add_generators. These routines will take a list of components, reallocate arrays and integrate the new components
    - [x] gens
    - [x] loads
    - [x] shunts
    - [x] buses
    - [x] branches
- [x] allow removing objects from the networks. Network will have routines that take lists of components and removes them from the network.
    - [x] gens
    - [x] loads
    - [x] shunts
    - [x] buses
    - [x] branches
- [x] allow networks to create subnetworks, for example by specifying a list of buses. An option of this would be to preserve generators and loads, i.e., move them to the nearest bus on the subnetwork
- **WARNING: adding an object of network2 to network1 will remove connections within network2 and will result in network1/network2 having objects that point to objects in network2/network1**
- **WARNING: after removing/adding some objects from the network, if some other objects not on the list given to delete/add the objects still exist, then they will point to invalid memory locations. This issue is not different than getting a network bus, then making the network object go out of scope and garbage collected, which results in the bus object having a c pointer pointing to garbage**

@awig Can you think of other useful functionality?

**Comment by awig** [comment]
Trying to catchup on things... a few ideas to through out:

- would the 3rd item include a function for creating subnetworks based on electrically disconnected portions of the overall network?
- adding areas to the pfnet network. the majority of the functionality could be handled by higher level packages, but it must to have areas (and maybe even owners) at a lower level for creating networks and equivalencing neighboring networks. For instance, some commercial solvers allow you to specify different tolerances for different areas so that one can specify lower precision in external areas.
- network equivalencing and/or disconnecting by areas. Depending if we add areas, could we implement network equivalencing algorithm(s) that would allow you to equivalence external areas?

Also, what is does OBC in particular?

This is all I can think of for now.

**Comment by ttinoco** [comment]
I think the items you mention are useful. The answer to your first question is yes. I think we should open issues for "areas, owners and a way to specify "weights"" for controlling accuracy. Network equivalencing can be part of this issue but maybe is better to treat it separately as it is likely very involved. Thanks!

**Comment by awig** [comment]
Sounds good to me. Yeah. I agree network equivalence-ing should be a separate issue. I can open a separate issue for it.

**Comment by ttinoco** [comment]
features available in branch "flexible_net"

**Comment by awig** [comment]
Nice! I'll have to play around with it soon.
