### ISSUE TITLE
Graph should display Bus IDs

### ISSUE THREAD

**Issue by martinzellner** [ttinoco/PFNET#5]
It would be nice if the Graph renders the Bus IDs as node labels.

**Comment by ttinoco** [comment]
Ok. I left this out since this did not look nice on huge graphs. I can make it an option. I believe now one can only set node attributes (see tables 8,9 in http://www.graphviz.org/doc/libguide/libguide.pdf) for all nodes but not for individual ones. The pfnet routine is graph.set_nodes_properties. I will create graph.set_node_property so one can set the "label" attribute of a specific node.

**Comment by ttinoco** [comment]
I have added graph.set_node_property. This routine allows setting graphviz-specific node attributes. Must be used before "set_layout". See updated visualization sample code (ex8.py)
[https://github.com/ttinoco/PFNET/blob/master/python/examples/ex8.py](url)
![graph](https://cloud.githubusercontent.com/assets/6379647/15119264/6559a4fc-1610-11e6-8a41-7bc4fa847c7b.png)

**Comment by martinzellner** [comment]
Looks really nice! Thanks!
